---
# tasks file for docker
- include_role:
    name: sanction

- name: Update all packages to the latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: install pre-apts
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: add gpg
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- name: add docker repo
  apt_repository:
    repo: "deb [arch={{deb_architecture.stdout}}] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable"
    state: present
    filename: docker
  notify: "update all"

- name: install docker 
  apt: 
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
      
- name: add user to docker group
  user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes   
  notify: "reset connection"

- name: set proxy for docker
  block:
    - name: create system directory for docker
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
      
    - name: add proxy.conf
      template:
        src: proxy.j2
        dest: /etc/systemd/system/docker.service.d/proxy.conf
        owner: root
        group: root
        mode: '0644'


- name: systemctl start and enable docker
  service: 
    name: docker
    state: started
    enabled: yes
