---
- name: test if you are under sanction
  uri:
    url: "{{ website }}"
    method: GET
    status_code: [403,200]
  register: result


- name: add shecan to resolv.conf 
  lineinfile:
    path: /etc/resolv.conf
    insertbefore: BOF
    line: "{{ dns }}"
  when: result.status == 403