---
# tasks file for init

- name: check if cluster is already running 
  shell: | 
    kubectl  cluster-info
  register: result
  ignore_errors: True

- name: fail the play if the previous command did not succeed
  when: "'refused' in result.stderr"
  block:

    - name: initial cluster
      become: true
      shell: |
        kubeadm init --pod-network-cidr {{ pod_network_cidr }} \
                  --apiserver-advertise-address {{ ansible_default_ipv4.address }} \
      register: init_cluster
    
    - name: Create Kubernetes config directory
      when: init_cluster is succeeded
      file:
        path: "{{ ansible_env.HOME  }}/.kube/"
        state: directory


    - name: Copy admin.conf to Home directory
      when: init_cluster is succeeded
      become: true
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ ansible_env.HOME  }}/.kube/config"
        owner: "{{ ansible_user | default(ansible_user_id) }}"
        group: "{{ ansible_user | default(ansible_user_id) }}"
        mode: 0755
        remote_src: true

- name: Deploy kubernetes dashboard into cluster
  become: true
  shell: |
     kubectl --kubeconfig=/etc/kubernetes/admin.conf  apply -f https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml

